- name: Setup Ansible Vault
  gather_facts: no
  hosts: localhost
  roles:
    - name: ansible_vault
      become: no
    - name: certificate
      become: no
  tasks:
    - name: Install community.docker
      ansible.builtin.command:
        cmd: ansible-galaxy collection install community.docker

    - name: Install community.mysql
      ansible.builtin.command:
        cmd: ansible-galaxy collection install community.mysql
