- name: Install Essential software
  hosts: all
  roles:
    - name: essentials
      become: yes

- name: Install Vaultwarden backend
  hosts: vault
  roles:
    - name: docker
      become: yes
    - name: vaultwarden
      become: yes

- name: Install HA Ingress server
  hosts: ingress
  roles:
    - name: nginx
      become: yes

- name: Init Database install
  hosts: database
  roles:
    - name: database
      become: yes

- name: Install Database Master
  hosts: database_master
  roles:
    - name: database/master
      become: yes
