- name: Generate random passwords
  set_fact:
    vault_secrets: |
      MYSQL_ROOT_PASSWORD: "{{ lookup('password', '/dev/null length=64') }}"
      MYSQL_PASSWORD: "{{ lookup('password', '/dev/null length=64') }}"
      MYSQL_REPL_PASSWORD: "{{ lookup('password', '/dev/null length=64') }}"
      ADMIN_TOKEN: "{{ lookup('password', '/dev/null length=64') }}"
  no_log: true  # Hide passwords in logs

- name: Create group_vars/all directory
  file:
    path: "./group_vars/all"
    state: directory
    mode: '0755'

- name: Save secrets to file
  copy:
    content: "{{ vault_secrets }}"
    dest: "./group_vars/all/secrets.yml"
    mode: '0600'

- name: Encrypt secrets.yml with Ansible Vault
  command: ansible-vault encrypt ./group_vars/all/secrets.yml
