- name: Create Vaultwarden database
  mysql_db:
    name: vaultwarden
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci
    state: present
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create Vaultwarden user
  mysql_user:
    name: vaultwarden
    password: "{{ MYSQL_PASSWORD }}"
    host: '%'
    state: present
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Grant privileges to Vaultwarden user
  mysql_user:
    name: vaultwarden
    host: '%'
    priv: "vaultwarden.*:ALL"
    state: present
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Grant additional specific privileges to Vaultwarden user
  mysql_user:
    name: vaultwarden
    host: '%'
    priv: "vaultwarden.*:ALTER,CREATE,DELETE,DROP,INDEX,INSERT,REFERENCES,SELECT,UPDATE, BINLOG MONITOR"
    state: present
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Comment out the bind-address directive in 50-server.cnf
  ansible.builtin.lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf  # Path to the config file
    regexp: '^bind-address'  # Regular expression to match the line starting with "bind-address"
    line: '#bind-address'  # Comment the line by adding a # at the beginning
    backup: yes  # Create a backup of the file before modifying it
