# Init Database
- name: Check if Vaultwarden database exists
  mysql_db:
    name: vaultwarden
    state: present
    login_user: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
  register: db_check

- name: Init Dataebase if non-exitnt
  include_tasks: init.yml
  when: db_check.failed

- name: Configure mariadb
  template:
    src: mysql.cnf.j2
    dest: /etc/mysql/conf.d/mysql.cnf

- name: Restart MariaDB
  service:
    name: mysql
    state: restarted
